#include "game_api.h"

void GameWin::load_settings()
{
    HKEY key;
    DWORD size;
    DWORD show_v;
    int left;
    int top;
    int width;
    int height;
    DWORD fx;
    DWORD f64;
    DWORD f68;
    DWORD f6c;
    DWORD f70;
    DWORD snd;
    DWORD mode_v;
    DWORD hs_e;
    DWORD w_e;
    DWORD l_e;
    DWORD sw_e;
    DWORD sl_e;
    DWORD sc_e;
    DWORD fw_e;
    DWORD hs_m;
    DWORD w_m;
    DWORD l_m;
    DWORD sw_m;
    DWORD sl_m;
    DWORD sc_m;
    DWORD fw_m;
    DWORD hs_d;
    DWORD w_d;
    DWORD l_d;
    DWORD sw_d;
    DWORD sl_d;
    DWORD sc_d;
    DWORD fw_d;
    RECT rc;

    left = CW_USEDEFAULT;
    top = CW_USEDEFAULT;
    width = CW_USEDEFAULT;
    height = CW_USEDEFAULT;
    fx = 1;
    f6c = 1;
    f70 = 1;
    snd = 1;
    mode_v = 1;
    show_v = SW_SHOWMAXIMIZED;
    f64 = 0;
    f68 = 0;
    hs_e = 0;
    w_e = 0;
    l_e = 0;
    sw_e = 0;
    sl_e = 0;
    sc_e = 0;
    fw_e = 0;
    hs_m = 0;
    w_m = 0;
    l_m = 0;
    sw_m = 0;
    sl_m = 0;
    sc_m = 0;
    fw_m = 0;
    hs_d = 0;
    w_d = 0;
    l_d = 0;
    sw_d = 0;
    sl_d = 0;
    sc_d = 0;
    fw_d = 0;
    if (RegOpenKeyExW(HKEY_CURRENT_USER, load_string(9), 0, KEY_READ, &key) == ERROR_SUCCESS) {
        size = 4;
        RegQueryValueExW(key, load_string(0xa), 0, 0, (BYTE *)&show_v, &size);
        RegQueryValueExW(key, load_string(0xb), 0, 0, (BYTE *)&left, &size);
        RegQueryValueExW(key, load_string(0xc), 0, 0, (BYTE *)&top, &size);
        RegQueryValueExW(key, load_string(0xd), 0, 0, (BYTE *)&width, &size);
        RegQueryValueExW(key, load_string(0xe), 0, 0, (BYTE *)&height, &size);
        RegQueryValueExW(key, load_string(0x15), 0, 0, (BYTE *)&fx, &size);
        RegQueryValueExW(key, load_string(0x16), 0, 0, (BYTE *)&f64, &size);
        RegQueryValueExW(key, load_string(0x17), 0, 0, (BYTE *)&f68, &size);
        RegQueryValueExW(key, load_string(0x18), 0, 0, (BYTE *)&f6c, &size);
        RegQueryValueExW(key, load_string(0x19), 0, 0, (BYTE *)&f70, &size);
        RegQueryValueExW(key, load_string(0x33), 0, 0, (BYTE *)&snd, &size);
        RegQueryValueExW(key, load_string(0x31), 0, 0, (BYTE *)&mode_v, &size);
        RegQueryValueExW(key, L"HighScore_Easy", 0, 0, (BYTE *)&hs_e, &size);
        RegQueryValueExW(key, L"Wins_Easy", 0, 0, (BYTE *)&w_e, &size);
        RegQueryValueExW(key, L"Losses_Easy", 0, 0, (BYTE *)&l_e, &size);
        RegQueryValueExW(key, L"StreakWins_Easy", 0, 0, (BYTE *)&sw_e, &size);
        RegQueryValueExW(key, L"StreakLosses_Easy", 0, 0, (BYTE *)&sl_e, &size);
        RegQueryValueExW(key, L"StreakCurrent_Easy", 0, 0, (BYTE *)&sc_e, &size);
        RegQueryValueExW(key, L"FWinStreak_Easy", 0, 0, (BYTE *)&fw_e, &size);
        RegQueryValueExW(key, L"HighScore_Medium", 0, 0, (BYTE *)&hs_m, &size);
        RegQueryValueExW(key, L"Wins_Medium", 0, 0, (BYTE *)&w_m, &size);
        RegQueryValueExW(key, L"Losses_Medium", 0, 0, (BYTE *)&l_m, &size);
        RegQueryValueExW(key, L"StreakWins_Medium", 0, 0, (BYTE *)&sw_m, &size);
        RegQueryValueExW(key, L"StreakLosses_Medium", 0, 0, (BYTE *)&sl_m, &size);
        RegQueryValueExW(key, L"StreakCurrent_Medium", 0, 0, (BYTE *)&sc_m, &size);
        RegQueryValueExW(key, L"FWinStreak_Medium", 0, 0, (BYTE *)&fw_m, &size);
        RegQueryValueExW(key, L"HighScore_Difficult", 0, 0, (BYTE *)&hs_d, &size);
        RegQueryValueExW(key, L"Wins_Difficult", 0, 0, (BYTE *)&w_d, &size);
        RegQueryValueExW(key, L"Losses_Difficult", 0, 0, (BYTE *)&l_d, &size);
        RegQueryValueExW(key, L"StreakWins_Difficult", 0, 0, (BYTE *)&sw_d, &size);
        RegQueryValueExW(key, L"StreakLosses_Difficult", 0, 0, (BYTE *)&sl_d, &size);
        RegQueryValueExW(key, L"StreakCurrent_Difficult", 0, 0, (BYTE *)&sc_d, &size);
        RegQueryValueExW(key, L"FWinStreak_Difficult", 0, 0, (BYTE *)&fw_d, &size);
        RegCloseKey(key);
    }
    show = show_v;
    rc.left = left;
    rc.top = top;
    rc.right = left + width;
    rc.bottom = top + height;
    wrect = rc;
    use_fx = fx;
    opt_f64 = f64;
    opt_f68 = f68;
    opt_f6c = f6c;
    opt_f70 = f70;
    play_snd = snd;
    suit_slot[0][0] = hs_e;
    suit_slot[0][1] = w_e;
    suit_slot[0][2] = l_e;
    suit_slot[0][3] = sw_e;
    suit_slot[0][4] = sl_e;
    suit_slot[0][6] = fw_e;
    suit_slot[1][0] = hs_m;
    suit_slot[1][1] = w_m;
    suit_slot[1][2] = l_m;
    suit_slot[1][3] = sw_m;
    suit_slot[1][4] = sl_m;
    suit_slot[1][6] = fw_m;
    suit_slot[2][0] = hs_d;
    suit_slot[2][1] = w_d;
    suit_slot[2][2] = l_d;
    suit_slot[2][3] = sw_d;
    suit_slot[2][4] = sl_d;
    suit_slot[2][6] = fw_d;
    *mode = mode_v;
}
