#!/usr/bin/env python3
"""Generate build.ninja and objdiff.json for the Spider PE matching project."""

from __future__ import annotations

import io
import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, TypedDict

from . import ninja_syntax
from .names import load_names

ROOT = Path(__file__).resolve().parents[1]


class Object:
    def __init__(self, completed: bool, name: str, **options: Any) -> None:
        self.name = name
        self.completed = completed
        self.options: Dict[str, Any] = {
            "cflags": None,
            "extra_cflags": [],
            "source": name,
            "src_dir": None,
            "progress_category": None,
            "lib": None,
        }
        self.options.update(options)
        self.src_path: Optional[Path] = None
        self.src_obj_path: Optional[Path] = None

    def resolve(self, config: "ProjectConfig", lib: Dict[str, Any]) -> "Object":
        obj = Object(self.completed, self.name, **lib)
        for key, value in self.options.items():
            if value is not None or key not in obj.options:
                obj.options[key] = value
        if obj.options["src_dir"] is None:
            obj.options["src_dir"] = config.src_dir
        if obj.options["cflags"] is None:
            obj.options["cflags"] = []
        obj.src_path = Path(obj.options["src_dir"]) / obj.options["source"]
        obj.src_obj_path = config.out_path() / "src" / Path(self.name).with_suffix(".obj")
        return obj


class ProgressCategory:
    def __init__(self, id: str, name: str) -> None:
        self.id = id
        self.name = name


class ProjectConfig:
    def __init__(self) -> None:
        self.build_dir = Path("build")
        self.src_dir = Path("src")
        self.tools_dir = Path("tools")
        self.version = "XPSP1"
        self.platform = "pe"
        self.config_path: Optional[Path] = None
        self.check_sha_path: Optional[Path] = None
        self.dtk_tag = "v0.0.29"
        self.objdiff_tag = "v3.8.2"
        self.dtk_path: Optional[Path] = None
        self.objdiff_path: Optional[Path] = None
        self.ninja_path: Optional[Path] = None
        self.wrapper: Optional[Path] = None
        self.cflags: List[str] = []
        self.ldflags: List[str] = []
        self.libs: List[Dict[str, Any]] = []
        self.progress = True
        self.progress_categories: List[ProgressCategory] = []
        self.warn_missing_source = True
        self.cards_dll = Path("orig/cards.dll")
        self.orig_exe = Path("orig/XPSP1/spider.exe")
        self.toolchain_dir = Path("orig/toolchain")
        self.units_path: Optional[Path] = None
        self.unit_info: Dict[str, Dict[str, Any]] = {}

    def out_path(self) -> Path:
        return self.build_dir / self.version

    def objects(self) -> Dict[str, Object]:
        out: Dict[str, Object] = {}
        for lib in self.libs:
            for obj in lib["objects"]:
                if obj.name in out:
                    sys.exit(f"Duplicate object name {obj.name}")
                resolved = obj.resolve(self, lib)
                out[obj.name] = resolved
        return out

    def validate(self) -> None:
        for attr in ("config_path", "check_sha_path", "version", "libs"):
            if getattr(self, attr) is None:
                sys.exit(f"ProjectConfig.{attr} missing")


class BuildConfigUnit(TypedDict):
    object: Optional[str]
    name: str
    autogenerated: bool


class BuildConfig(TypedDict, total=False):
    version: str
    name: str
    units: List[BuildConfigUnit]


def is_windows() -> bool:
    return os.name == "nt"


def make_flags_str(flags: List[str]) -> str:
    return " ".join(flags)


def toolchain_cl(config: ProjectConfig) -> Optional[Path]:
    candidates = [
        config.toolchain_dir / "bin" / "cl.exe",
        config.toolchain_dir / "BIN" / "cl.exe",
        config.toolchain_dir / "cl.exe",
        config.toolchain_dir / "VC7" / "bin" / "cl.exe",
        config.toolchain_dir / "VC7" / "BIN" / "cl.exe",
        config.toolchain_dir / "bin" / "x86" / "cl.exe",
    ]
    for path in candidates:
        if path.is_file():
            return path
    return None


def load_unit_info(path: Optional[Path]) -> Dict[str, Dict[str, Any]]:
    if path is None or not path.is_file():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        return {}
    return {str(u["name"]): u for u in data if isinstance(u, dict) and "name" in u}


def load_build_config(path: Path) -> Optional[BuildConfig]:
    if not path.is_file():
        return None
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, dict):
        return None
    return data  # type: ignore[return-value]


def generate_build(config: ProjectConfig) -> None:
    config.validate()
    objects = config.objects()
    if config.units_path is not None and not config.unit_info:
        config.unit_info = load_unit_info(config.units_path)
    build_path = config.out_path()
    build_path.mkdir(parents=True, exist_ok=True)
    tools_path = config.build_dir / "tools"
    tools_path.mkdir(parents=True, exist_ok=True)
    build_config_path = build_path / "config.json"
    build_config = load_build_config(build_config_path)

    python = sys.executable
    download_tool = config.tools_dir / "download_tool.py"
    wrapper = config.wrapper or (config.tools_dir / "wine_msvc.sh")
    if not is_windows() and not wrapper.is_file():
        sys.exit(f"Wine wrapper missing: {wrapper}")

    out = io.StringIO()
    n = ninja_syntax.Writer(out)
    n.variable("ninja_required_version", "1.3")
    n.variable("python", python)
    n.variable("configure_args", " ".join(sys.argv[1:]))
    n.newline()

    n.comment("Download pinned tools")
    n.rule(
        name="download_tool",
        command=f"$python {download_tool} --tool $tool --tag $tag --output $out",
        description="DOWNLOAD $tool $tag",
        restat=True,
    )
    n.newline()

    if config.dtk_path is not None and config.dtk_path.is_file():
        dtk = config.dtk_path
        dtk_implicit: Optional[Path] = None
    else:
        dtk = tools_path / "dtk"
        dtk_implicit = dtk
        n.build(
            outputs=dtk,
            rule="download_tool",
            implicit=download_tool,
            variables={"tool": "dtk", "tag": config.dtk_tag},
        )
    if config.objdiff_path is not None and config.objdiff_path.is_file():
        objdiff = config.objdiff_path
        objdiff_implicit: Optional[Path] = None
    else:
        objdiff = tools_path / "objdiff-cli"
        objdiff_implicit = objdiff
        n.build(
            outputs=objdiff,
            rule="download_tool",
            implicit=download_tool,
            variables={"tool": "objdiff-cli", "tag": config.objdiff_tag},
        )
    n.newline()

    n.comment("Split original PE into relocatable COFF objects")
    n.rule(
        name="split",
        command=f"{dtk} coff split --no-update $in $out_dir"
        f" && $python tools/fix_bss.py $out_dir {Path('config') / config.version / 'splits.txt'}",
        description="SPLIT $in",
        depfile="$out_dir/dep",
        deps="gcc",
        restat=True,
    )
    n.build(
        outputs=build_config_path,
        rule="split",
        inputs=config.config_path,
        implicit=[
            dtk,
            config.config_path,
            Path("config") / config.version / "splits.txt",
            Path("config") / config.version / "symbols.txt",
            Path("tools") / "fix_bss.py",
        ],
        variables={"out_dir": build_path},
    )
    n.newline()

    n.comment("MSVC 7.0 via Wine")
    n.rule(
        name="cl",
        command=f"{wrapper} cl /nologo $cflags /c $in /Fo$out",
        description="CL $out",
    )
    n.rule(
        name="link",
        command=f"{wrapper} link $ldflags /OUT:$out $in",
        description="LINK $out",
    )
    n.rule(
        name="copy",
        command="$python -c 'import shutil,sys; shutil.copyfile(sys.argv[1], sys.argv[2])' $in $out",
        description="COPY $out",
    )
    n.newline()

    source_objs: List[Path] = []
    all_source: List[Path] = []
    missing_source: List[str] = []
    for obj in objects.values():
        assert obj.src_path is not None and obj.src_obj_path is not None
        if not obj.src_path.is_file():
            missing_source.append(str(obj.src_path))
            continue
        obj.src_obj_path.parent.mkdir(parents=True, exist_ok=True)
        cflags = list(obj.options["cflags"] or []) + list(obj.options["extra_cflags"] or [])
        implicit_inputs: List[Path] = [wrapper]
        # Quoted .cpp includes are same-TU bodies (ecx preservation). cl has no
        # depfile, so list them or ninja will not rebuild the caller.
        src_text = obj.src_path.read_text(encoding="utf-8", errors="replace")
        for inc in re.findall(r'#include\s+"([^"]+\.cpp)"', src_text):
            sibling = obj.src_path.parent / inc
            if sibling.is_file():
                implicit_inputs.append(sibling)
        n.build(
            outputs=obj.src_obj_path,
            rule="cl",
            inputs=obj.src_path,
            implicit=implicit_inputs,
            variables={"cflags": make_flags_str(cflags)},
        )
        # link:false keeps a second copy for objdiff without LNK2005.
        # The caller's TU provides the symbol that is actually linked.
        if config.unit_info.get(obj.name, {}).get("link", True):
            source_objs.append(obj.src_obj_path)
        all_source.append(obj.src_obj_path)
        n.newline()

    if missing_source and config.warn_missing_source:
        for path in missing_source:
            print(f"warning: missing source {path}")

    n.build(outputs="all_source", rule="phony", inputs=all_source)
    n.newline()

    n.comment("Original resources, so LoadString/LoadBitmap work on the rebuilt module")
    n.rule(
        name="extract_res",
        command="$python tools/extract_res.py $in $out",
        description="RES $out",
    )
    n.rule(
        name="cvtres",
        command=f"{wrapper} cvtres /nologo /MACHINE:IX86 /OUT:$out $in",
        description="CVTRES $out",
    )
    res_path = build_path / "spider.res"
    res_obj = build_path / "spider_res.obj"
    n.build(outputs=res_path, rule="extract_res", inputs=config.orig_exe,
            implicit=Path("tools") / "extract_res.py")
    n.build(outputs=res_obj, rule="cvtres", inputs=res_path, implicit=wrapper)
    n.newline()

    extra_objs = [res_obj]

    exe_path = build_path / "spider.exe"
    n.build(
        outputs=exe_path,
        rule="link",
        inputs=source_objs + extra_objs,
        implicit=wrapper,
        variables={"ldflags": make_flags_str(config.ldflags)},
    )
    cards_out = build_path / "cards.dll"
    if config.cards_dll.is_file():
        n.build(
            outputs=cards_out,
            rule="copy",
            inputs=config.cards_dll,
        )
    n.build(
        outputs="spider",
        rule="phony",
        inputs=[exe_path, cards_out] if config.cards_dll.is_file() else [exe_path],
    )
    n.newline()

    # Runnable variant: same objects, linked away from 0x01000000 so the
    # harness in winmain.cpp can map the original image at its own base.
    n.comment("Runnable build (not the matching target)")
    run_exe = build_path / "run" / "spider.exe"
    run_ldflags = [
        "/BASE:0x00400000" if f.startswith("/BASE:") else f
        for f in config.ldflags
        if not f.startswith("/MAP:")
    ]
    n.build(
        outputs=run_exe,
        rule="link",
        inputs=source_objs + extra_objs,
        implicit=wrapper,
        variables={"ldflags": make_flags_str(run_ldflags)},
    )
    n.build(outputs="spider_run", rule="phony", inputs=[run_exe])
    n.newline()

    n.comment("SHA-1 of a matching rebuild (fails until the exe matches)")
    n.rule(
        name="sha1check",
        command=f"shasum -a 1 -c {config.check_sha_path}",
        description="SHA1 $in",
    )
    n.build(
        outputs="check",
        rule="sha1check",
        inputs=exe_path,
        implicit=config.check_sha_path,
    )
    n.newline()

    report_path = build_path / "report.json"
    n.comment("objdiff progress report")
    n.rule(
        name="report",
        command=f"{objdiff} report generate -o $out",
        description="REPORT $out",
    )
    n.build(
        outputs=report_path,
        rule="report",
        implicit=[objdiff, "objdiff.json", "all_source"],
    )
    n.newline()

    n.comment("Reconfigure when the split config or generator changes")
    n.rule(
        name="configure",
        command="$python configure.py $configure_args",
        generator=True,
        description="RUN configure.py",
    )
    n.build(
        outputs=["build.ninja", "objdiff.json"],
        rule="configure",
        implicit=[
            build_config_path,
            Path("configure.py"),
            Path("tools/project.py"),
            Path("tools/ninja_syntax.py"),
            config.config_path,
            *([config.units_path] if config.units_path else []),
        ],
    )
    n.newline()

    n.build(
        outputs="tools",
        rule="phony",
        inputs=[dtk, objdiff],
    )
    n.newline()

    cl_path = toolchain_cl(config)
    if cl_path is None:
        print(
            "warning: MSVC toolchain not found under orig/toolchain/. "
            "Ninja will download dtk/objdiff and split, but cl.exe will fail until "
            "you install VC7.0 13.00.9178 (see orig/README.md). "
            "Use: ninja tools && ninja  # split only"
        )
        n.default([build_config_path, "tools"])
    else:
        print(f"Using compiler at {cl_path}")
        n.default(["all_source", exe_path])

    with open("build.ninja", "w", encoding="utf-8") as fh:
        fh.write(out.getvalue())

    generate_objdiff_config(
        config, objects, build_config, build_path, has_compiler=cl_path is not None
    )
    print("Wrote build.ninja and objdiff.json")


def expected_obj_path(build_path: Path, unit_name: str) -> Path:
    p = Path(unit_name)
    return build_path / p.with_suffix(".o")


def generate_objdiff_config(
    config: ProjectConfig,
    objects: Dict[str, Object],
    build_config: Optional[BuildConfig],
    build_path: Path,
    has_compiler: bool = False,
) -> None:
    ninja = str(config.ninja_path) if config.ninja_path else "ninja"
    units: List[Dict[str, Any]] = []
    by_name = objects
    info = config.unit_info

    def metadata_for(name: str, obj: Optional[Object], autogenerated: bool) -> Dict[str, Any]:
        meta = info.get(name, {})
        kind = meta.get("kind")
        complete = bool(meta.get("complete"))
        if obj is not None:
            complete = bool(obj.completed)
        elif autogenerated or kind in ("thunks", "rdata", "crt"):
            # rsrc/data leftovers and identified CRT are not decompiled.
            complete = True if autogenerated or kind in ("thunks", "rdata") else complete
        category = meta.get("category")
        if obj and obj.options.get("progress_category"):
            category = obj.options["progress_category"]
        metadata: Dict[str, Any] = {
            "complete": complete,
            "auto_generated": autogenerated,
        }
        if obj and obj.src_path:
            metadata["source_path"] = str(obj.src_path)
        elif meta.get("source"):
            metadata["source_path"] = str(Path(config.src_dir) / meta["source"])
        if category:
            metadata["progress_categories"] = [category] if isinstance(category, str) else category
        return metadata

    labels = load_names(Path("config") / config.version / "names.txt")

    if build_config and build_config.get("units"):
        for unit in build_config["units"]:
            name = unit["name"]
            obj = by_name.get(name)
            label = labels.get(Path(name).stem)
            entry: Dict[str, Any] = {"name": label or name}
            target = unit.get("object")
            if target:
                entry["target_path"] = target
            else:
                entry["target_path"] = str(expected_obj_path(build_path, name))
            if obj and obj.src_obj_path and (has_compiler or obj.src_obj_path.is_file()):
                entry["base_path"] = str(obj.src_obj_path)
            entry["metadata"] = metadata_for(name, obj, bool(unit.get("autogenerated")))
            units.append(entry)
    else:
        for obj in objects.values():
            entry = {
                "name": obj.name,
                "target_path": str(expected_obj_path(build_path, obj.name)),
                "metadata": metadata_for(obj.name, obj, False),
            }
            if obj.src_obj_path and (has_compiler or obj.src_obj_path.is_file()):
                entry["base_path"] = str(obj.src_obj_path)
            units.append(entry)

    objdiff_config: Dict[str, Any] = {
        "$schema": "https://raw.githubusercontent.com/encounter/objdiff/main/config.schema.json",
        "min_version": "2.0.0",
        "custom_make": ninja,
        "build_target": True,
        "build_base": has_compiler,
        "watch_patterns": [
            "*.c",
            "*.cpp",
            "*.h",
            "*.py",
            "*.yml",
            "*.txt",
            "*.json",
        ],
        "ignore_patterns": ["build/**/*", "orig/**/*", "tools/wineprefix/**/*"],
        "progress_categories": [
            {"id": cat.id, "name": cat.name} for cat in config.progress_categories
        ],
        "units": units,
    }
    with open("objdiff.json", "w", encoding="utf-8") as fh:
        json.dump(objdiff_config, fh, indent=2)
        fh.write("\n")


def calculate_progress(config: ProjectConfig) -> None:
    report = config.out_path() / "report.json"
    if not report.is_file():
        print("No report.json yet. Run: ninja && ninja build/XPSP1/report.json")
        return
    with open(report, encoding="utf-8") as fh:
        data = json.load(fh)
    measures = data.get("measures") or data
    print(json.dumps(measures, indent=2) if isinstance(measures, dict) else data)
