#!/usr/bin/env python3
"""Generate build.ninja and objdiff.json for the Spider PE matching project."""

from __future__ import annotations

import io
import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, TypedDict

from . import ninja_syntax
from .modules import Module
from .names import load_names

ROOT = Path(__file__).resolve().parents[1]


class Object:
    def __init__(self, completed: bool, name: str, **options: Any) -> None:
        self.name = name
        self.completed = completed
        self.module: Optional[Module] = None
        self.options: Dict[str, Any] = {
            "cflags": None,
            "extra_cflags": [],
            "source": name,
            "src_dir": None,
            "progress_category": None,
            "lib": None,
        }
        self.options.update(options)
        self.src_path: Optional[Path] = None
        self.src_obj_path: Optional[Path] = None

    def resolve(self, module: Module) -> "Object":
        obj = Object(self.completed, self.name, **self.options)
        obj.module = module
        if obj.options["cflags"] is None:
            obj.options["cflags"] = list(module.cflags)
        obj.src_path = module.src_dir / obj.options["source"]
        obj.src_obj_path = module.src_obj_dir / Path(self.name).with_suffix(".obj")
        return obj


class ProgressCategory:
    def __init__(self, id: str, name: str) -> None:
        self.id = id
        self.name = name


class ProjectConfig:
    def __init__(self) -> None:
        self.build_dir = Path("build")
        self.tools_dir = Path("tools")
        self.version = "XPSP1"
        self.platform = "pe"
        self.dtk_tag = "v0.0.29"
        self.objdiff_tag = "v3.8.2"
        self.dtk_path: Optional[Path] = None
        self.objdiff_path: Optional[Path] = None
        self.ninja_path: Optional[Path] = None
        self.wrapper: Optional[Path] = None
        self.progress = True
        self.progress_categories: List[ProgressCategory] = []
        self.warn_missing_source = True
        self.toolchain_dir = Path("orig/toolchain")
        self.modules: List[Module] = []
        self.module_objects: Dict[str, Dict[str, Object]] = {}
        self.module_units: Dict[str, Dict[str, Dict[str, Any]]] = {}
        self.module_assets: Dict[str, List[Path]] = {}

    def out_path(self) -> Path:
        return self.build_dir / self.version

    def validate(self) -> None:
        if not self.modules:
            sys.exit("ProjectConfig.modules missing")


class BuildConfigUnit(TypedDict):
    object: Optional[str]
    name: str
    autogenerated: bool


class BuildConfig(TypedDict, total=False):
    version: str
    name: str
    units: List[BuildConfigUnit]


def is_windows() -> bool:
    return os.name == "nt"


def make_flags_str(flags: List[str]) -> str:
    return " ".join(flags)


def toolchain_cl(config: ProjectConfig) -> Optional[Path]:
    candidates = [
        config.toolchain_dir / "bin" / "cl.exe",
        config.toolchain_dir / "BIN" / "cl.exe",
        config.toolchain_dir / "cl.exe",
        config.toolchain_dir / "VC7" / "bin" / "cl.exe",
        config.toolchain_dir / "VC7" / "BIN" / "cl.exe",
        config.toolchain_dir / "bin" / "x86" / "cl.exe",
    ]
    for path in candidates:
        if path.is_file():
            return path
    return None


def load_unit_info(path: Optional[Path]) -> Dict[str, Dict[str, Any]]:
    if path is None or not path.is_file():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        return {}
    return {str(u["name"]): u for u in data if isinstance(u, dict) and "name" in u}


def load_build_config(path: Path) -> Optional[BuildConfig]:
    if not path.is_file():
        return None
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, dict):
        return None
    return data  # type: ignore[return-value]


def objects_for_module(module: Module, units: Dict[str, Dict[str, Any]]) -> Dict[str, Object]:
    out: Dict[str, Object] = {}
    kind = module.progress_category
    for unit in units.values():
        if unit.get("kind") != kind or not unit.get("source"):
            continue
        obj = Object(
            bool(unit.get("complete")),
            unit["name"],
            source=unit["source"],
            progress_category=kind,
            cflags=list(module.cflags),
        ).resolve(module)
        out[obj.name] = obj
    for name, source, category in module.extra_sources:
        obj = Object(
            False,
            name,
            source=source,
            progress_category=category,
            cflags=list(module.cflags),
        ).resolve(module)
        out[obj.name] = obj
    return out


def generate_build(config: ProjectConfig) -> None:
    config.validate()
    tools_path = config.build_dir / "tools"
    tools_path.mkdir(parents=True, exist_ok=True)
    for module in config.modules:
        module.build_dir.mkdir(parents=True, exist_ok=True)
        module.src_obj_dir.mkdir(parents=True, exist_ok=True)

    python = sys.executable
    download_tool = config.tools_dir / "download_tool.py"
    wrapper = config.wrapper or (config.tools_dir / "wine_msvc.sh")
    if not is_windows() and not wrapper.is_file():
        sys.exit(f"Wine wrapper missing: {wrapper}")

    out = io.StringIO()
    n = ninja_syntax.Writer(out)
    n.variable("ninja_required_version", "1.3")
    n.variable("python", python)
    n.variable("configure_args", " ".join(sys.argv[1:]))
    n.newline()

    n.comment("Download pinned tools")
    n.rule(
        name="download_tool",
        command=f"$python {download_tool} --tool $tool --tag $tag --output $out",
        description="DOWNLOAD $tool $tag",
        restat=True,
    )
    n.newline()

    if config.dtk_path is not None and config.dtk_path.is_file():
        dtk = config.dtk_path
    else:
        dtk = tools_path / "dtk"
        n.build(
            outputs=dtk,
            rule="download_tool",
            implicit=download_tool,
            variables={"tool": "dtk", "tag": config.dtk_tag},
        )
    if config.objdiff_path is not None and config.objdiff_path.is_file():
        objdiff = config.objdiff_path
    else:
        objdiff = tools_path / "objdiff-cli"
        n.build(
            outputs=objdiff,
            rule="download_tool",
            implicit=download_tool,
            variables={"tool": "objdiff-cli", "tag": config.objdiff_tag},
        )
    n.newline()

    n.comment("Split original PE into relocatable COFF objects")
    n.rule(
        name="split",
        command=f"{dtk} coff split --no-update $in $out_dir"
        f" && $python tools/fix_bss.py $out_dir $splits",
        description="SPLIT $in",
        depfile="$out_dir/dep",
        deps="gcc",
        restat=True,
    )
    n.newline()

    n.comment("MSVC 7.0 via Wine")
    n.rule(
        name="cl",
        command=f"{wrapper} cl /nologo $cflags /c $in /Fo$out",
        description="CL $out",
    )
    n.rule(
        name="link",
        command=f"{wrapper} link $ldflags /OUT:$out $in",
        description="LINK $out",
    )
    n.rule(
        name="lib_def",
        command=f"{wrapper} lib /nologo /MACHINE:I386 /DEF:$def /OUT:$implib $in",
        description="LIB $out",
    )
    n.rule(
        name="rc",
        command=f"{wrapper} rc /i $assets /fo $out $in",
        description="RC $out",
    )
    n.rule(
        name="cvtres",
        command=f"{wrapper} cvtres /nologo /MACHINE:IX86 /OUT:$out $in",
        description="CVTRES $out",
    )
    n.newline()

    n.comment("Byte-compare a rebuilt image with gold, ignoring bind and link time (fails until it matches)")
    n.rule(
        name="imagecheck",
        command="$python tools/cmp_image.py $gold $in",
        description="CHECK $in",
    )
    n.newline()

    n.comment("objdiff progress report, one per module")
    n.rule(
        name="report",
        command=f"{objdiff} report generate -p $project -o $out",
        description="REPORT $out",
    )
    n.newline()

    all_source: List[Path] = []
    missing_source: List[str] = []
    default_outputs: List[Path] = []
    configure_implicit: List[Path] = [
        Path("configure.py"),
        Path("tools/project.py"),
        Path("tools/modules.py"),
        Path("tools/ninja_syntax.py"),
        Path("tools/extract_assets.py"),
        Path("tools/pe_rsrc.py"),
    ]
    check_inputs: List[Path] = []
    report_inputs: List[Path] = []
    module_sources: Dict[str, List[Path]] = {}

    for module in config.modules:
        objects = config.module_objects.get(module.name, {})
        units = config.module_units.get(module.name, {})
        assets = config.module_assets.get(module.name, [])
        source_objs: List[Path] = []
        run_objs: List[Path] = []

        n.comment(f"{module.name} ({module.orig})")
        n.build(
            outputs=module.build_config,
            rule="split",
            inputs=module.config_yml,
            implicit=[
                dtk,
                module.config_yml,
                module.splits,
                module.symbols,
                Path("tools") / "fix_bss.py",
            ],
            variables={"out_dir": module.build_dir, "splits": module.splits},
        )
        configure_implicit.append(module.build_config)
        configure_implicit.append(module.config_yml)
        configure_implicit.append(module.units_json)
        configure_implicit.append(module.orig)
        n.newline()

        for obj in objects.values():
            assert obj.src_path is not None and obj.src_obj_path is not None
            if not obj.src_path.is_file():
                missing_source.append(str(obj.src_path))
                continue
            cflags = list(obj.options["cflags"] or []) + list(obj.options["extra_cflags"] or [])
            implicit_inputs: List[Path] = [wrapper]
            src_text = obj.src_path.read_text(encoding="utf-8", errors="replace")
            for inc in re.findall(r'#include\s+"([^"]+\.cpp)"', src_text):
                sibling = obj.src_path.parent / inc
                if sibling.is_file():
                    implicit_inputs.append(sibling)
            n.build(
                outputs=obj.src_obj_path,
                rule="cl",
                inputs=obj.src_path,
                implicit=implicit_inputs,
                variables={"cflags": make_flags_str(cflags)},
            )
            if obj.name in module.run_only:
                run_objs.append(obj.src_obj_path)
            elif units.get(obj.name, {}).get("link", True):
                source_objs.append(obj.src_obj_path)
            all_source.append(obj.src_obj_path)
            module_sources.setdefault(module.name, []).append(obj.src_obj_path)
            n.newline()

        extra_objs: List[Path] = []
        if module.res_script.is_file():
            n.build(
                outputs=module.res_path,
                rule="rc",
                inputs=module.res_script,
                implicit=[wrapper, *assets],
                variables={"assets": module.assets_dir},
            )
            n.build(outputs=module.res_obj, rule="cvtres", inputs=module.res_path, implicit=wrapper)
            extra_objs.append(module.res_obj)
            n.newline()

        link_implicit: List[Path] = [wrapper]
        link_objs = extra_objs + source_objs if module.res_first else source_objs + extra_objs
        if module.def_file is not None:
            n.build(
                outputs=module.exp_path,
                rule="lib_def",
                inputs=link_objs,
                implicit=[wrapper, module.def_file],
                implicit_outputs=module.implib_path,
                variables={"def": module.def_file, "implib": module.implib_path},
            )
            link_objs = [module.exp_path] + link_objs
        n.build(
            outputs=module.output,
            rule="link",
            inputs=link_objs,
            implicit=link_implicit,
            variables={"ldflags": make_flags_str(module.ldflags)},
        )
        n.build(outputs=module.name, rule="phony", inputs=[module.output])
        default_outputs.append(module.output)
        n.newline()

        if module.runnable_base is not None:
            run_exe = module.build_dir / "run" / module.output_name
            run_ldflags = [
                f"/BASE:0x{module.runnable_base:08X}" if f.startswith("/BASE:") else f
                for f in module.ldflags
                if not f.startswith(("/MAP:", "/PDB", "/DEBUG"))
            ]
            n.build(
                outputs=run_exe,
                rule="link",
                inputs=source_objs + run_objs + extra_objs,
                implicit=wrapper,
                variables={"ldflags": make_flags_str(run_ldflags)},
            )
            n.build(outputs=f"{module.name}_run", rule="phony", inputs=[run_exe])
            n.newline()

        n.build(
            outputs=f"check_{module.name}",
            rule="imagecheck",
            inputs=module.output,
            implicit=[Path("tools") / "cmp_image.py", module.orig],
            variables={"gold": module.orig},
        )
        check_inputs.append(Path(f"check_{module.name}"))
        n.build(
            outputs=module.report,
            rule="report",
            implicit=[objdiff, module.objdiff_json, *module_sources.get(module.name, [])],
            variables={"project": module.build_dir},
        )
        n.build(outputs=f"report_{module.name}", rule="phony", inputs=[module.report])
        report_inputs.append(module.report)
        n.newline()

    if missing_source and config.warn_missing_source:
        for path in missing_source:
            print(f"warning: missing source {path}")

    n.build(outputs="all_source", rule="phony", inputs=all_source)
    n.build(outputs="check", rule="phony", inputs=check_inputs)
    n.build(outputs="report", rule="phony", inputs=report_inputs)
    n.newline()

    n.comment("Reconfigure when the split config or generator changes")
    n.rule(
        name="configure",
        command="$python configure.py $configure_args",
        generator=True,
        description="RUN configure.py",
    )
    n.build(
        outputs=["build.ninja", "objdiff.json", *(m.objdiff_json for m in config.modules)],
        rule="configure",
        implicit=configure_implicit,
    )
    n.newline()

    n.build(outputs="tools", rule="phony", inputs=[dtk, objdiff])
    n.newline()

    cl_path = toolchain_cl(config)
    if cl_path is None:
        print(
            "warning: MSVC toolchain not found under orig/toolchain/. "
            "Ninja will download dtk/objdiff and split, but cl.exe will fail until "
            "you install VC7.0 13.00.9178 (see orig/README.md). "
            "Use: ninja tools && ninja  # split only"
        )
        n.default([mod.build_config for mod in config.modules] + ["tools"])
    else:
        print(f"Using compiler at {cl_path}")
        n.default(["all_source", *default_outputs])

    with open("build.ninja", "w", encoding="utf-8") as fh:
        fh.write(out.getvalue())

    generate_objdiff_config(config, has_compiler=cl_path is not None)
    print("Wrote build.ninja and objdiff.json")


def expected_obj_path(build_path: Path, unit_name: str) -> Path:
    p = Path(unit_name)
    return build_path / p.with_suffix(".o")


def generate_objdiff_config(config: ProjectConfig, has_compiler: bool = False) -> None:
    ninja = str(config.ninja_path) if config.ninja_path else "ninja"
    units: List[Dict[str, Any]] = []
    module_units: Dict[str, List[Dict[str, Any]]] = {}

    for module in config.modules:
        first_unit = len(units)
        objects = config.module_objects.get(module.name, {})
        info = config.module_units.get(module.name, {})
        build_config = load_build_config(module.build_config)
        labels = load_names(module.names)

        def metadata_for(name: str, obj: Optional[Object], autogenerated: bool) -> Dict[str, Any]:
            meta = info.get(name, {})
            kind = meta.get("kind")
            complete = bool(meta.get("complete"))
            if obj is not None:
                complete = bool(obj.completed)
            elif autogenerated or kind in ("thunks", "rdata", "crt"):
                complete = True if autogenerated or kind in ("thunks", "rdata") else complete
            category = meta.get("category")
            if obj and obj.options.get("progress_category"):
                category = obj.options["progress_category"]
            metadata: Dict[str, Any] = {
                "complete": complete,
                "auto_generated": autogenerated,
            }
            if obj and obj.src_path:
                metadata["source_path"] = str(obj.src_path)
            elif meta.get("source"):
                metadata["source_path"] = str(module.src_dir / meta["source"])
            if category:
                metadata["progress_categories"] = [category] if isinstance(category, str) else category
            return metadata

        if build_config and build_config.get("units"):
            for unit in build_config["units"]:
                name = unit["name"]
                obj = objects.get(name)
                label = labels.get(Path(name).stem)
                entry: Dict[str, Any] = {"name": f"{module.name}/{label or name}"}
                target = unit.get("object")
                if target:
                    entry["target_path"] = target
                else:
                    entry["target_path"] = str(expected_obj_path(module.build_dir, name))
                if obj and obj.src_obj_path and (has_compiler or obj.src_obj_path.is_file()):
                    entry["base_path"] = str(obj.src_obj_path)
                entry["metadata"] = metadata_for(name, obj, bool(unit.get("autogenerated")))
                units.append(entry)
        else:
            for obj in objects.values():
                entry = {
                    "name": f"{module.name}/{obj.name}",
                    "target_path": str(expected_obj_path(module.build_dir, obj.name)),
                    "metadata": metadata_for(obj.name, obj, False),
                }
                if obj.src_obj_path and (has_compiler or obj.src_obj_path.is_file()):
                    entry["base_path"] = str(obj.src_obj_path)
                units.append(entry)
        module_units[module.name] = units[first_unit:]

    objdiff_config: Dict[str, Any] = {
        "$schema": "https://raw.githubusercontent.com/encounter/objdiff/main/config.schema.json",
        "min_version": "2.0.0",
        "custom_make": ninja,
        "build_target": True,
        "build_base": has_compiler,
        "watch_patterns": [
            "*.c",
            "*.cpp",
            "*.h",
            "*.py",
            "*.yml",
            "*.txt",
            "*.json",
        ],
        "ignore_patterns": ["build/**/*", "orig/**/*", "tools/wineprefix/**/*"],
        "progress_categories": [
            {"id": cat.id, "name": cat.name} for cat in config.progress_categories
        ],
        "units": units,
    }
    with open("objdiff.json", "w", encoding="utf-8") as fh:
        json.dump(objdiff_config, fh, indent=2)
        fh.write("\n")

    # Report-only projects: objdiff resolves unit paths against the project
    # directory, so each module's copy is rebased onto its build directory.
    for module in config.modules:
        base = module.build_dir

        def rebase(path: str) -> str:
            return os.path.relpath(path, base)

        mod_units = []
        used_categories = set()
        for unit in module_units.get(module.name, []):
            entry = dict(unit)
            for key in ("target_path", "base_path"):
                if key in entry:
                    entry[key] = rebase(entry[key])
            meta = dict(entry.get("metadata", {}))
            if "source_path" in meta:
                meta["source_path"] = rebase(meta["source_path"])
            used_categories.update(meta.get("progress_categories", []))
            entry["metadata"] = meta
            mod_units.append(entry)
        module_config = {
            "$schema": objdiff_config["$schema"],
            "min_version": objdiff_config["min_version"],
            "build_target": False,
            "build_base": False,
            "progress_categories": [
                {"id": cat.id, "name": cat.name}
                for cat in config.progress_categories
                if cat.id in used_categories
            ],
            "units": mod_units,
        }
        base.mkdir(parents=True, exist_ok=True)
        with open(module.objdiff_json, "w", encoding="utf-8") as fh:
            json.dump(module_config, fh, indent=2)
            fh.write("\n")


def calculate_progress(config: ProjectConfig) -> None:
    for module in config.modules:
        report = module.report
        print(f"{module.name} ({module.orig}):")
        if not report.is_file():
            print(f"  no report yet. Run: ninja report_{module.name}")
            continue
        with open(report, encoding="utf-8") as fh:
            data = json.load(fh)
        measures = data.get("measures") or data
        text = json.dumps(measures, indent=2) if isinstance(measures, dict) else str(data)
        print("\n".join("  " + line for line in text.splitlines()))
